### ISSUE TITLE
Issue with running make package on OS X

### ISSUE THREAD

**Issue by rossistboss** [DHowett/theos#117]
I installed dpkg with MacPorts on OS X. When I run make package, it fails saying: 
du: invalid option -- 'I'

I investigated a bit, and traced the problem to Darwin.mk. For _THEOS_PLATFORM_DU_EXCLUDE, it has "-I". I then compared Darwin.mk to Darwin-arm.mk. For the same key Darwin-arm.mk has "--exclude". 

I switched out "-I" in Darwin.mk for "--exclude". I then ran make package again, and it perfectly built a package. 

If this is the right fix for this problem, please consider changing it in Darwin.mk to 
"--exclude".

**Comment by DHowett** [comment]
Theos expects "du" to be the du shipped with OS X, not one overridden by
macports or homebrew.

**Comment by rossistboss** [comment]
My mistake. You were right. Turns out I was using du from the homebrew updated coreutils.

**Comment by DHowett** [comment]
There are rather many reasons that Homebrew is ineffective. This is one such reason.
